name: marqueer
description: A powerful and customizable Flutter widget that transforms any widget into a smooth scrolling marquee with support for multiple directions, user interactions, and programmatic control. Perfect for displaying scrolling text, images, or any content with configurable speed, direction, and interaction behavior.
version: 2.2.1
homepage: https://github.com/GeceGibi/marqueer

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^10.0.0
  
flutter:
